os: Windows
language: cpp
git:
    quiet: true

cache:
    directories:
    - $HOME/AppData/Local/Temp/chocolatey
    - /C/tools/msys64

before_install:
- |-
    [[ ! -f C:/tools/msys64/msys2_shell.cmd ]] && rm -rf C:/tools/msys64
    choco uninstall -y mingw
    choco upgrade --no-progress -y msys2
    export msys2='cmd //C RefreshEnv.cmd '
    export msys2+='& set MSYS=winsymlinks:nativestrict '
    export msys2+='& C:\\tools\\msys64\\msys2_shell.cmd -defterm -no-start'
    export mingw64="$msys2 -mingw64 -full-path -here -c "\"\$@"\" --"
    export msys2+=" -msys2 -c "\"\$@"\" --"
    $msys2 pacman --sync --noconfirm --needed mingw-w64-x86_64-toolchain
    taskkill //IM gpg-agent.exe //F
    export PATH=/C/tools/msys64/mingw64/bin:$PATH
    export MAKE=mingw32-make
    $msys2 pacman -S --noconfirm mingw-w64-x86_64-qt5-static mingw-w64-x86_64-boost mingw-w64-x86_64-rapidjson

script: 
- |-
    cd ./SEFMediaPreparer
    qmake -makefile
    mingw32-make

before_cache:
- |-
    $msys2 pacman --sync --clean --noconfirm
